<?php

namespace Franbella\Bundle\SiteBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContatoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContatoRepository extends EntityRepository
{
    
    public function listarTodos($limite = null)
    {
        $qb = $this->createQueryBuilder('c')
                   ->select('c')
                   ->addOrderBy('c.dataEnvio');

        if (false === is_null($limite))
            $qb->setMaxResults($limite);

        return $qb->getQuery()
                  ->getResult();
    }
    
    public function listarTodosNaoLidos($limite = null)
    {
        $qb = $this->createQueryBuilder('c')
                   ->select('c')
                   ->where("c.lida = 0")
                   ->addOrderBy('c.dataEnvio');

        if (false === is_null($limite))
            $qb->setMaxResults($limite);

        return $qb->getQuery()
                  ->getResult();
    }
    
}
