<?php

namespace Franbella\Bundle\SiteBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DistribuidorFornecedorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistribuidorFornecedorRepository extends EntityRepository
{
}
