<?php

namespace Franbella\Bundle\SiteBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DistribuidorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistribuidorRepository extends EntityRepository
{
    
    public function listarTodos($limite = null)
    {
        $qb = $this->createQueryBuilder('d')
                   ->select('d')
                   ->addOrderBy('d.razaoSocial');

        if (false === is_null($limite))
            $qb->setMaxResults($limite);

        return $qb->getQuery()
                  ->getResult();
    }
    
    public function carregar($id_distribuidor)
    {
        $qb = $this->createQueryBuilder('d')
                   ->select('d, df')
                   ->leftJoin('FranbellaSiteBundle:DistribuidorFornecedor', 'df')
                   ->where('df.distribuidor = d.id')
                   ->andWhere('d.id = :distribuidor')
                   ->setParameter(':distribuidor', $id_distribuidor)
                   ->addOrderBy('d.razaoSocial');

        return $qb->getQuery()
                  ->getResult();
    }
    
}
