<?php

namespace Franbella\Bundle\SiteBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EstadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoRepository extends EntityRepository
{
    
    public function listarTodosAtivos($limite = null)
    {
        $qb = $this->createQueryBuilder('e')
                   ->select('e')
                   ->where('e.ativo = 0')
                   ->addOrderBy('e.nome');

        if (false === is_null($limite))
            $qb->setMaxResults($limite);

        return $qb->getQuery()
                  ->getResult();
    }
    
}
