<?php

namespace Franbella\Bundle\SiteBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendaRepository extends EntityRepository
{
    
    public function listaCidades(){
        $qb = $this->createQueryBuilder('v')
            ->select('v.cidade, v.uf')
            ->distinct()
            ->orderBy('v.cidade')
//            ->getQuery()
            ;

        return $qb;
    }
    
}
