parameters:
#    franbella_site.example.class: Franbella\Bundle\SiteBundle\Example

services:
#    franbella_site.example:
#        class: %franbella_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
