<?php

namespace Franbella\Bundle\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AgendaFotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgendaFotoRepository extends EntityRepository
{
    
    public function listarTodos($limite = null, $id_evento = null)
    {
        $qb = $this->createQueryBuilder('af')
                   ->select('af')
                ->andWhere('af.agenda = :id_agenda')
                ->setParameter('id_agenda', $id_evento)
                ;

        if (false === is_null($limite))
            $qb->setMaxResults($limite);

        return $qb->getQuery()
                  ->getResult();
    }
    
    public function excluirTodosPorEvento($id_evento)
    {
        $qb = $this->createQueryBuilder('af')
                   ->delete('FranbellaAdminBundle:AgendaFoto', 'af')
                ->andWhere('af.agenda = :id_agenda')
                ->setParameter('id_agenda', $id_evento)
                ;

        return $qb->getQuery()
                  ->execute();
    }
    
}
