<?php

namespace Franbella\Bundle\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TipoPDVRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoPDVRepository extends EntityRepository
{
    
    public function listarTodos($limite = null)
    {
        $qb = $this->createQueryBuilder('d')
                   ->select('d')
                   ->addOrderBy('d.nome');

        if (false === is_null($limite))
            $qb->setMaxResults($limite);

        return $qb->getQuery()
                  ->getResult();
    }
    
}
