parameters:
#    franbella_admin.example.class: Franbella\Bundle\AdminBundle\Example

services:
#    franbella_admin.example:
#        class: %franbella_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
